AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
BLUETOOTH_ENABLE = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
#if defined(KEYBOARD_keebio_iris_rev4)
ENCODER_ENABLE = yes
#else
ENCODER_ENABLE = no
#endif
EXTRAKEY_ENABLE = yes
MIDI_ENABLE = no
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = no
RGBLIGHT_ENABLE = yes
TAP_DANCE_ENABLE = no
UNICODE_ENABLE = no
